import '@/styles/globals.css'
import { Toaster } from '@/components/ui/toaster'
import ThemeWrapper from '@/components/ThemeWrapper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ko' className='antialiased'>
      <body className='antialiased'>
        <ThemeWrapper>
          <div className='h-screen p-4'>{children}</div>
          <Toaster />
        </ThemeWrapper>
      </body>
    </html>
  )
}
