import '@/styles/globals.css'
import { Toaster } from '@/components/ui/toaster'
import ThemeWrapper from '@/components/ThemeWrapper'
import { Header } from '@/components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ko' className='antialiased'>
      <body>
        <ThemeWrapper>
          <div className='h-screen'>
            <div className='w-full h-full relative mx-auto rounded border overflow-y-scroll dark:border-slate-700  shadow'>
              <Header />
              <div className='p-4'>{children}</div>
            </div>
          </div>
          <Toaster />
        </ThemeWrapper>
      </body>
    </html>
  )
}
