import '@/styles/globals.css'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ko' className='antialiased'>
      <body className='antialiased'>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
